### ISSUE TITLE
It is wrong when we use different ANE

### ISSUE THREAD

**Issue by flashomer** [myflashlab/common-dependencies-ANE#27]
Please Help me! 

hi, I use different ANE and in this way, I get the error.

androidSupport-v4.ane = http://prntscr.com/l6geiv
overrideAir.ane = http://prntscr.com/l6gjq8
androidSupport-core.ane = http://prntscr.com/l6gi8z

http://prntscr.com/l6gfew

the program does not work when you remove any of them. :/

extensions:

<extensionID>com.distriqt.MediaPlayer</extensionID>
<extensionID>com.distriqt.androidsupport.AppCompatV7</extensionID>
<extensionID>com.distriqt.androidsupport.V4</extensionID>
<extensionID>com.myflashlab.air.extensions.permissionCheck</extensionID>
<extensionID>com.myflashlab.air.extensions.webView</extensionID>
<extensionID>com.myflashlab.air.extensions.dependency.androidSupport.v4</extensionID>
<extensionID>com.myflashlab.air.extensions.dependency.overrideAir</extensionID>
<extensionID>com.myflashlab.air.extensions.dependency.androidSupport.core</extensionID>

**Comment by myflashlab** [comment]
hmm, you should probably remove AndroidSupport dependencies from the other provider and use ours.

**Comment by pis0** [comment]
Is it expected?

android logcat stacks related to overrideAir:


`
11-26 17:26:05.537 32736 32736 W System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
11-26 17:26:05.543 32736 32736 W System.err:    at com.myflashlab.dependency.overrideAir.AirCommand.decode(AirCommand.java:93)
11-26 17:26:05.543 32736 32736 W System.err:    at com.myflashlab.dependency.overrideAir.AirCommand.call(AirCommand.java:58)
11-26 17:26:05.543 32736 32736 W System.err:    at com.adobe.air.Entrypoints.EntryMainWrapper(Native Method)
11-26 17:26:05.543 32736 32736 W System.err:    at com.adobe.air.Entrypoints.EntryMain(Entrypoints.java:139)
11-26 17:26:05.543 32736 32736 W System.err:    at com.adobe.air.AndroidActivityWrapper.LaunchApplication(AndroidActivityWrapper.java:1167)
11-26 17:26:05.543 32736 32736 W System.err:    at com.adobe.air.AndroidActivityWrapper.onSurfaceInitialized(AndroidActivityWrapper.java:1416)
11-26 17:26:05.543 32736 32736 W System.err:    at com.adobe.air.AIRWindowSurfaceView.surfaceChanged(AIRWindowSurfaceView.java:790)
11-26 17:26:05.543 32736 32736 W System.err:    at android.view.SurfaceView.updateWindow(SurfaceView.java:594)
11-26 17:26:05.544 32736 32736 W System.err:    at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:177)
11-26 17:26:05.544 32736 32736 W System.err:    at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:944)
11-26 17:26:05.544 32736 32736 W System.err:    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2055)
11-26 17:26:05.544 32736 32736 W System.err:    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
11-26 17:26:05.544 32736 32736 W System.err:    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6013)
11-26 17:26:05.544 32736 32736 W System.err:    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
11-26 17:26:05.544 32736 32736 W System.err:    at android.view.Choreographer.doCallbacks(Choreographer.java:670)
11-26 17:26:05.544 32736 32736 W System.err:    at android.view.Choreographer.doFrame(Choreographer.java:606)
11-26 17:26:05.545 32736 32736 W System.err:    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
11-26 17:26:05.545 32736 32736 W System.err:    at android.os.Handler.handleCallback(Handler.java:739)
11-26 17:26:05.545 32736 32736 W System.err:    at android.os.Handler.dispatchMessage(Handler.java:95)
11-26 17:26:05.545 32736 32736 W System.err:    at android.os.Looper.loop(Looper.java:148)
11-26 17:26:05.545 32736 32736 W System.err:    at android.app.ActivityThread.main(ActivityThread.java:5417)
11-26 17:26:05.545 32736 32736 W System.err:    at java.lang.reflect.Method.invoke(Native Method)
11-26 17:26:05.545 32736 32736 W System.err:    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
11-26 17:26:05.545 32736 32736 W System.err:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
11-26 17:26:05.545 32736 32736 I ooo     : End of input at character 0 of
11-26 17:26:05.545 32736 32736 W System.err: org.json.JSONException: End of input at character 0 of
11-26 17:26:05.546 32736 32736 W System.err:    at org.json.JSONTokener.syntaxError(JSONTokener.java:449)
11-26 17:26:05.546 32736 32736 W System.err:    at org.json.JSONTokener.nextValue(JSONTokener.java:97)
11-26 17:26:05.546 32736 32736 W System.err:    at org.json.JSONObject.<init>(JSONObject.java:156)
11-26 17:26:05.546 32736 32736 W System.err:    at org.json.JSONObject.<init>(JSONObject.java:173)
11-26 17:26:05.546 32736 32736 W System.err:    at com.myflashlab.dependency.overrideAir.AirCommand.call(AirCommand.java:58)
11-26 17:26:05.546 32736 32736 W System.err:    at com.adobe.air.Entrypoints.EntryMainWrapper(Native Method)
11-26 17:26:05.546 32736 32736 W System.err:    at com.adobe.air.Entrypoints.EntryMain(Entrypoints.java:139)
11-26 17:26:05.546 32736 32736 W System.err:    at com.adobe.air.AndroidActivityWrapper.LaunchApplication(AndroidActivityWrapper.java:1167)
11-26 17:26:05.546 32736 32736 W System.err:    at com.adobe.air.AndroidActivityWrapper.onSurfaceInitialized(AndroidActivityWrapper.java:1416)
11-26 17:26:05.546 32736 32736 W System.err:    at com.adobe.air.AIRWindowSurfaceView.surfaceChanged(AIRWindowSurfaceView.java:790)
11-26 17:26:05.546 32736 32736 W System.err:    at android.view.SurfaceView.updateWindow(SurfaceView.java:594)
11-26 17:26:05.546 32736 32736 W System.err:    at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:177)
11-26 17:26:05.546 32736 32736 W System.err:    at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:944)
11-26 17:26:05.546 32736 32736 W System.err:    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2055)
11-26 17:26:05.546 32736 32736 W System.err:    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
11-26 17:26:05.546 32736 32736 W System.err:    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6013)
11-26 17:26:05.546 32736 32736 W System.err:    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
11-26 17:26:05.546 32736 32736 W System.err:    at android.view.Choreographer.doCallbacks(Choreographer.java:670)
11-26 17:26:05.546 32736 32736 W System.err:    at android.view.Choreographer.doFrame(Choreographer.java:606)
11-26 17:26:05.546 32736 32736 W System.err:    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
11-26 17:26:05.547 32736 32736 W System.err:    at android.os.Handler.handleCallback(Handler.java:739)
11-26 17:26:05.547 32736 32736 W System.err:    at android.os.Handler.dispatchMessage(Handler.java:95)
11-26 17:26:05.547 32736 32736 W System.err:    at android.os.Looper.loop(Looper.java:148)
11-26 17:26:05.547 32736 32736 W System.err:    at android.app.ActivityThread.main(ActivityThread.java:5417)
11-26 17:26:05.547 32736 32736 W System.err:    at java.lang.reflect.Method.invoke(Native Method)
11-26 17:26:05.547 32736 32736 W System.err:    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
11-26 17:26:05.547 32736 32736 W System.err:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
`

**Comment by myflashlab** [comment]
@pis0 will you please open this issue in a new thread so we can get to it?
