### ISSUE TITLE
Intellij idea gives GC overhead limit exceeded

### ISSUE THREAD

**Issue by JamesSmith2** [myflashlab/common-dependencies-ANE#38]
Hello,

I'm using intellij idea 2018.2.4 version with latest FCM/Android ANE-s it gives me this error:
When using older library, no issues appears, only with latest FCM/Android library ane-s.
I have set memory heap up-to 12000mb, still same error.
Also i'm using AIRSDK32 latest 103 build

`dx tool failed:
UNEXPECTED TOP-LEVEL ERROR:
java.lang.OutOfMemoryError: GC overhead limit exceeded
	at com.android.dx.util.FixedSizeList.<init>(FixedSizeList.java:38)
	at com.android.dx.rop.code.RegisterSpecList.<init>(RegisterSpecList.java:102)
	at com.android.dx.ssa.RegisterMapper.map(RegisterMapper.java:50)
	at com.android.dx.ssa.NormalSsaInsn.mapSourceRegisters(NormalSsaInsn.java:48)
	at com.android.dx.ssa.SsaInsn.mapRegisters(SsaInsn.java:161)
	at com.android.dx.ssa.SsaMethod.mapRegisters(SsaMethod.java:394)
	at com.android.dx.ssa.back.SsaToRop.moveParametersToHighRegisters(SsaToRop.java:235)
	at com.android.dx.ssa.back.SsaToRop.convert(SsaToRop.java:118)
	at com.android.dx.ssa.back.SsaToRop.convertToRopMethod(SsaToRop.java:69)
	at com.android.dx.ssa.Optimizer.optimize(Optimizer.java:101)
	at com.android.dx.ssa.Optimizer.optimize(Optimizer.java:72)
	at com.android.dx.dex.cf.CfTranslator.processMethods(CfTranslator.java:297)
	at com.android.dx.dex.cf.CfTranslator.translate0(CfTranslator.java:137)
	at com.android.dx.dex.cf.CfTranslator.translate(CfTranslator.java:93)
	at com.android.dx.command.dexer.Main.processClass(Main.java:734)
	at com.android.dx.command.dexer.Main.processFileBytes(Main.java:678)
	at com.android.dx.command.dexer.Main.access$300(Main.java:83)
	at com.android.dx.command.dexer.Main$1.processFileBytes(Main.java:607)
	at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)
	at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
	at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
	at com.android.dx.command.dexer.Main.processOne(Main.java:637)
	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:506)
	at com.android.dx.command.dexer.Main.runMultiDex(Main.java:335)
	at com.android.dx.command.dexer.Main.run(Main.java:245)
	at com.android.dx.command.dexer.Main.main(Main.java:215)
	at com.android.dx.command.Main.main(Main.java:106)
`

**Comment by myflashlab** [comment]
This is what happens with intelliJ IDEA and not directly related to ANEs! However, the solution is to increase the heapsize so it won't run out of memory.

in your ```.idea``` folder in intelliJ project setup, open the file ```flexCompiler.xml``` and add the following component:

```xml
  <component name="FlexCompilerConfiguration">
    <option name="HEAP_SIZE_MB" value="2048" />
  </component>
```

for more information about this, you must contact the intelliJ team.
