### ISSUE TITLE
overrideAir ANE causing confict with Distriqt ANEs

### ISSUE THREAD

**Issue by Selonie** [myflashlab/common-dependencies-ANE#4]
Hi
I recently updated a whole bunch of your ANEs and everything seems to be working well on your side, but the Share ANE  from Distriqt that I have been using for a few years now prevents the app compiling. 

If I comment out your OverideAir ANE the app compiles without errors but your googleplay ANE doesn't work.

The Distriqt error is ................

`dx tool failed:
UNEXPECTED TOP-LEVEL EXCEPTION:
java.lang.IllegalArgumentException: already added: Lcom/adobe/air/ActivityResult
Callback;
        at com.android.dx.dex.file.ClassDefsSection.add(ClassDefsSection.java:122)
        at com.android.dx.dex.file.DexFile.add(DexFile.java:161)
        at com.android.dx.command.dexer.Main.processClass(Main.java:737)
        at com.android.dx.command.dexer.Main.processFileBytes(Main.java:678)
        at com.android.dx.command.dexer.Main.access$300(Main.java:83)
        at com.android.dx.command.dexer.Main$1.processFileBytes(Main.java:607)
        at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)
        at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
        at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
        at com.android.dx.command.dexer.Main.processOne(Main.java:637)
        at com.android.dx.command.dexer.Main.processAllFiles(Main.java:511)
        at com.android.dx.command.dexer.Main.runMonoDex(Main.java:281)
        at com.android.dx.command.dexer.Main.run(Main.java:247)
        at com.android.dx.command.dexer.Main.main(Main.java:215)
        at com.android.dx.command.Main.main(Main.java:106)
1 error; aborting`

Distriqt say 

> That definition is an AIR wrapper interface that is essential for several of our ANEs

Everything worked well together until I recently updated when adding firebase.
Is there a fix for this? 
Do myFlashLabs happen to have an ANE that brings up the Native share dialogue box I could use instead?
Thanks

**Comment by myflashlab** [comment]
As far as conflicts with other ANE developers, the best we could do was to let others use our dependencies to avoid such conflicts. So, if other ANE developers are not using them, there's nothing we can do.

Anyway, building a native share window is in our to-do list and you'll know as soon as it's ready. We are currently focused on the Firebase...
