### ISSUE TITLE
App crashes even after using your google play services common ANEs

### ISSUE THREAD

**Issue by appearance** [myflashlab/common-dependencies-ANE#7]
Hi, I am creating my own ANE which uses google maps api v.3. I am using MapFragment in my FragmentActivity.  I have used the following anes from your common ane list (latest):
googlePlayServices_base.ane,
googlePlayServices_basement.ane,
googlePlayServices_location.ane,
googlePlayServices_maps.ane,
googlePlayServices_places.ane.

I am using adobe animate cc 2017. It builds the apk successfully but when my fragment activity is invoked, it crashes throwing below error:
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.R$styleable" on path: DexPathList[[zip file "/data/app/my.app.package.test-1/base.apk"],nativeLibraryDirectories=[/data/app/air.my.app.package.test-1/lib/arm, /vendor/lib, /system/lib]]
                                                     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                     at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                     at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                     at com.google.android.gms.maps.GoogleMapOptions.createFromAttributes(Unknown Source) 
                                                     at com.google.android.gms.maps.MapFragment.onInflate(Unknown Source) 
                                                     at android.app.FragmentManagerImpl.onCreateView(FragmentManager.java:2117) 
                                                     at android.app.Activity.onCreateView(Activity.java:5348) 
                                                     at android.support.v4.app.BaseFragmentActivityHoneycomb.onCreateView(BaseFragmentActivityHoneycomb.java:36) 
                                                     at android.support.v4.app.FragmentActivity.onCreateView(FragmentActivity.java:75) 
                                                     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:733) 
...

Can you tell me if I am missing any more dependency libraries?

(Please note that I am using latest AIR SDK ver. 25.0.0.136) I have tried with AIR SDB 26.0 BETA also.

Your help in this regard is highly appreciated.

Thank you.

**Comment by myflashlab** [comment]
I think you are probably missing the androidSupport.ane. Try that.

**Comment by appearance** [comment]
I have added androidSupport.ane too, but the error still persists. I tried to poke into the apk and found that it's trying to find the class at 'com.google.android.gms.R$stylable' but I think it exists at 'com.google.android.gms.maps.R$stylable' .  Kindly note that in dec'2014, this kind of bug was there and a bug report was filed ([bug report](https://issuetracker.google.com/issues/35825520)).  I hope it's not getting repeated again in the newest versions.  Kindly elaborate on which versions you have used at the time of compiling these ANEs:
1. Google Repository Version.
2. SDK Tools version
3. Built Tools version
4. Any other info related to this.

Please note that currently I am using Adobe AIR SDK v.25.0.0.136.  If I look into the 'runtimeClasses.jar' file from 'AIR SDK 25.0.0\lib\android\lib\' folder, I found R.java exists in 'com.google.android.gms'.  Is it causing the problem? If yes, how can I fix this?  

Please note that, just to overcome this bug situation, I used SupportMapFragment class and instantiated in the code instead of using it through xml layout.  This way, it works.

Kindly look into the matter and help fix this bug.

Thank you.

**Comment by 4malik** [comment]
I started new issue https://github.com/myflashlab/common-dependencies-ANE/issues/12
and than see that issue so i think its probably common problem with googlePlayServices update,
